version: '3'

services:
  app1:
    build: .
    ports:
      - "5078:5078"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.16.238.10

  app2:
    build: .
    ports:
      - "5079:5078"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.16.238.11

  app3:
    build: .
    ports:
      - "5080:5078"
    volumes:
      - .:/app
    networks:
      app_network:
        ipv4_address: 172.16.238.12

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.16.238.0/24

