version: '3'

services:
  app1:
    build: .
    environment:
      - DATABASE_URI=sqlite:///node_data1.db
    ports:
      - "5078:5078"
    volumes:
      - .:/app
      - ~/logs/app1:/app/logs
      - ~/logs/initial_node1.json:/app/initial_node.json
    networks:
      app_network:
        ipv4_address: 172.16.238.10

  app2:
    build: .
    environment:
      - DATABASE_URI=sqlite:///node_data2.db
    ports:
      - "5079:5078"
    volumes:
      - .:/app
      - ~/logs/app2:/app/logs
      - ~/logs/initial_node2.json:/app/initial_node.json
    networks:
      app_network:
        ipv4_address: 172.16.238.11

  app3:
    build: .
    environment:
      - DATABASE_URI=sqlite:///node_data3.db
    ports:
      - "5080:5078"
    volumes:
      - .:/app
      - ~/logs/app3:/app/logs
      - ~/logs/initial_node3.json:/app/initial_node.json
    networks:
      app_network:
        ipv4_address: 172.16.238.12

networks:
  app_network:
    ipam:
      config:
        - subnet: 172.16.238.0/24

